### PR TITLE
Stop services on looping call errors

### PR DESCRIPTION
**Pull request by justinvdm**
We want our services to stop so that the thing managing their processes can restart them.

### CODE REVIEW

**Comment by justinvdm** [comment]
Ready for review.

**Comment by hodgestar** [comment]
Travis failed with:
```
  File "/home/travis/build/praekelt/vumi-http-retry-api/vumi_http_retry/workers/maintainer/tests/test_worker.py", line 218, in test_on_error
    worker = yield self.mk_worker()
exceptions.TypeError: mk_worker() takes exactly 2 arguments (1 given)
```

**Comment by justinvdm** [comment]
Ready for re-review.

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
